[2024-11-10T14:21:19.011+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-10T14:21:19.035+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-11-08T00:00:00+00:00 [queued]>
[2024-11-10T14:21:19.045+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-11-08T00:00:00+00:00 [queued]>
[2024-11-10T14:21:19.045+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-10T14:21:19.063+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_book_data> on 2024-11-08 00:00:00+00:00
[2024-11-10T14:21:19.080+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5879) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T14:21:19.084+0000] {standard_task_runner.py:72} INFO - Started process 5887 to run task
[2024-11-10T14:21:19.085+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'fetch_book_data', 'scheduled__2024-11-08T00:00:00+00:00', '--job-id', '691', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmp366_cvyk']
[2024-11-10T14:21:19.086+0000] {standard_task_runner.py:105} INFO - Job 691: Subtask fetch_book_data
[2024-11-10T14:21:19.156+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-11-08T00:00:00+00:00 [running]> on host 0afc8c4a15bb
[2024-11-10T14:21:19.277+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='fetch_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-08T00:00:00+00:00'
[2024-11-10T14:21:19.280+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-10T14:21:19.280+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-10T14:21:19.281+0000] {logging_mixin.py:190} INFO - Current task name:fetch_book_data state:running start_date:2024-11-10 14:21:19.036304+00:00
[2024-11-10T14:21:19.281+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books and current dag run status:running
[2024-11-10T14:21:19.281+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-10T14:21:20.175+0000] {app.py:32} ERROR - Failed to retrieve page 1: 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=data+engineering+books&page=1
[2024-11-10T14:21:20.203+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-10T14:21:20.221+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-10T14:21:20.221+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-11-08T00:00:00+00:00, execution_date=20241108T000000, start_date=20241110T142119, end_date=20241110T142120
[2024-11-10T14:21:20.235+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-10T14:21:20.235+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-10T14:21:20.235+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books queued_at:2024-11-10 14:21:16.060147+00:00
[2024-11-10T14:21:20.235+0000] {logging_mixin.py:190} INFO - Task hostname:0afc8c4a15bb operator:PythonOperator
[2024-11-10T14:21:20.263+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-10T14:21:20.292+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-10T14:21:20.294+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
