[2024-11-10T14:15:17.114+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-10T14:15:17.137+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-10-19T00:00:00+00:00 [queued]>
[2024-11-10T14:15:17.150+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-10-19T00:00:00+00:00 [queued]>
[2024-11-10T14:15:17.151+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-10T14:15:17.164+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_book_data> on 2024-10-19 00:00:00+00:00
[2024-11-10T14:15:17.176+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5473) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T14:15:17.177+0000] {standard_task_runner.py:72} INFO - Started process 5483 to run task
[2024-11-10T14:15:17.180+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'fetch_book_data', 'scheduled__2024-10-19T00:00:00+00:00', '--job-id', '610', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpycp3vsc8']
[2024-11-10T14:15:17.181+0000] {standard_task_runner.py:105} INFO - Job 610: Subtask fetch_book_data
[2024-11-10T14:15:17.245+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-10-19T00:00:00+00:00 [running]> on host 0afc8c4a15bb
[2024-11-10T14:15:17.358+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='fetch_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-19T00:00:00+00:00'
[2024-11-10T14:15:17.360+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-10T14:15:17.360+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-10T14:15:17.360+0000] {logging_mixin.py:190} INFO - Current task name:fetch_book_data state:running start_date:2024-11-10 14:15:17.138516+00:00
[2024-11-10T14:15:17.360+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books and current dag run status:running
[2024-11-10T14:15:17.360+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-10T14:15:18.624+0000] {app.py:32} ERROR - Failed to retrieve page 1: 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=data+engineering+books&page=1
[2024-11-10T14:15:18.650+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-10T14:15:18.668+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-10T14:15:18.668+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-10-19T00:00:00+00:00, execution_date=20241019T000000, start_date=20241110T141517, end_date=20241110T141518
[2024-11-10T14:15:18.684+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-10T14:15:18.685+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-10T14:15:18.685+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books queued_at:2024-11-10 14:15:13.778057+00:00
[2024-11-10T14:15:18.685+0000] {logging_mixin.py:190} INFO - Task hostname:0afc8c4a15bb operator:PythonOperator
[2024-11-10T14:15:18.717+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-10T14:15:18.756+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-10T14:15:18.758+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
