[2024-11-10T14:14:06.109+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-10T14:14:06.133+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-11-10T14:14:06.142+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-11-10T14:14:06.142+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-10T14:14:06.157+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_book_data> on 2024-10-04 00:00:00+00:00
[2024-11-10T14:14:06.170+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5288) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T14:14:06.172+0000] {standard_task_runner.py:72} INFO - Started process 5294 to run task
[2024-11-10T14:14:06.174+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'fetch_book_data', 'scheduled__2024-10-04T00:00:00+00:00', '--job-id', '565', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpb2jltgcq']
[2024-11-10T14:14:06.175+0000] {standard_task_runner.py:105} INFO - Job 565: Subtask fetch_book_data
[2024-11-10T14:14:06.244+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-10-04T00:00:00+00:00 [running]> on host 0afc8c4a15bb
[2024-11-10T14:14:06.372+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='fetch_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T00:00:00+00:00'
[2024-11-10T14:14:06.374+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-10T14:14:06.375+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-10T14:14:06.375+0000] {logging_mixin.py:190} INFO - Current task name:fetch_book_data state:running start_date:2024-11-10 14:14:06.133964+00:00
[2024-11-10T14:14:06.375+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books and current dag run status:running
[2024-11-10T14:14:06.375+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-10T14:14:27.557+0000] {app.py:32} ERROR - Failed to retrieve page 1: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[2024-11-10T14:14:27.590+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-10T14:14:27.607+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-10T14:14:27.607+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-10-04T00:00:00+00:00, execution_date=20241004T000000, start_date=20241110T141406, end_date=20241110T141427
[2024-11-10T14:14:27.618+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-10T14:14:27.619+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-10T14:14:27.619+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books queued_at:2024-11-10 14:14:04.040651+00:00
[2024-11-10T14:14:27.619+0000] {logging_mixin.py:190} INFO - Task hostname:0afc8c4a15bb operator:PythonOperator
[2024-11-10T14:14:27.641+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-10T14:14:27.679+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-10T14:14:27.680+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
