[2024-11-10T14:15:36.631+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-10T14:15:36.667+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-11-10T14:15:36.685+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-11-10T14:15:36.685+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-10T14:15:36.713+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_book_data> on 2024-10-21 00:00:00+00:00
[2024-11-10T14:15:36.737+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5534) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T14:15:36.741+0000] {standard_task_runner.py:72} INFO - Started process 5544 to run task
[2024-11-10T14:15:36.741+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'fetch_book_data', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '622', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmp5ht7kebd']
[2024-11-10T14:15:36.742+0000] {standard_task_runner.py:105} INFO - Job 622: Subtask fetch_book_data
[2024-11-10T14:15:36.834+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-10-21T00:00:00+00:00 [running]> on host 0afc8c4a15bb
[2024-11-10T14:15:36.967+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='fetch_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-21T00:00:00+00:00'
[2024-11-10T14:15:36.969+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-10T14:15:36.969+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-10T14:15:36.970+0000] {logging_mixin.py:190} INFO - Current task name:fetch_book_data state:running start_date:2024-11-10 14:15:36.667577+00:00
[2024-11-10T14:15:36.970+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books and current dag run status:running
[2024-11-10T14:15:36.970+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-10T14:15:37.906+0000] {app.py:32} ERROR - Failed to retrieve page 1: 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=data+engineering+books&page=1
[2024-11-10T14:15:37.936+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-10T14:15:37.953+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-10T14:15:37.954+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-10-21T00:00:00+00:00, execution_date=20241021T000000, start_date=20241110T141536, end_date=20241110T141537
[2024-11-10T14:15:37.972+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-10T14:15:37.973+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-10T14:15:37.973+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_amazon_books queued_at:2024-11-10 14:15:33.663062+00:00
[2024-11-10T14:15:37.973+0000] {logging_mixin.py:190} INFO - Task hostname:0afc8c4a15bb operator:PythonOperator
[2024-11-10T14:15:38.003+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-10T14:15:38.046+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-10T14:15:38.048+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
